---
engines:
  duplication:
    enabled: true
    config:
      languages:
      - javascript
  eslint:
    enabled: true
  fixme:
    enabled: true
  shellcheck:
    enabled: true
ratings:
  paths:
  - "**.js"
exclude_paths:
- .vagrant/
- config/
- tmp/
- "**/node_modules/**"
