extends: 'eslint:recommended'
env:
  es6: true
  mocha: true
  node: true
rules:
  indent:
    - error
    - 2
  linebreak-style:
    - error
    - unix
  no-console: 0
  semi:
    - error
    - always
