resources:
- name: code 
  type: git
  source:
    uri: {{target-repo}}
- name: scripts 
  type: git
  source:
    uri: https://github.com/18F/concourse-compliance-testing.git 
- name: collector
  type: s3
  source:
    bucket: concourse-collector
    regexp: bandit.json
    access_key_id: {{aws-access-key}}
    secret_access_key: {{aws-secret-key}}

jobs:
- name: compliance-scan 
  plan:
  - get: code 
  - get: scripts 
  - task: scan-bandit
    file: scripts/task-bandit.yml
  - put: collector
    params:
      from: results
