resources:
- name: code 
  type: git
  source:
    uri: {{target-repo}}
- name: scripts 
  type: git
  source:
    uri: https://github.com/DavidEBest/concourse-compliance-testing.git 
- name: collector
  type: s3
  source:
    bucket: concourse-collector
    regexp: (bandit|zap).(?P<version>.*).(json|txt)
    access_key_id: {{aws-access-key}}
    secret_access_key: {{aws-secret-key}}

jobs:
- name: python-scan 
  plan:
  - get: code 
  - get: scripts 
  - task: scan-bandit
    file: scripts/task-bandit.yml
  - put: collector
    params:
      to: ekip/
      from: results/bandit.(.*).json

- name: zap-scan 
  plan:
  - get: scripts 
  - task: scan-owasp
    file: scripts/task-owasp.yml
    config:
      params:
        LIVE_TARGET: {{live-target}}
  - put: collector
    params:
      to: ekip/
      from: results/zap.(.*).txt

