resources:
- name: code 
  type: git
  source:
    uri: {{target-repo}}
- name: scripts 
  type: git
  source:
    uri: https://github.com/DavidEBest/concourse-compliance-testing.git 
- name: zap-collector
  type: s3
  source:
    bucket: concourse-collector
    versioned_file: {{aws-zap}}
    access_key_id: {{aws-access-key}}
    secret_access_key: {{aws-secret-key}}
- name: bandit-collector
  type: s3
  source:
    bucket: concourse-collector
    versioned_file: {{aws-bandit}}
    access_key_id: {{aws-access-key}}
    secret_access_key: {{aws-secret-key}}

jobs:
- name: python-scan 
  plan:
  - get: code 
  - get: scripts 
  - task: scan-bandit
    file: scripts/task-bandit.yml
  - put: bandit-collector
    params:
      to: {{aws-folder}}
      from: results/bandit.json

- name: zap-scan 
  plan:
  - get: scripts 
  - task: scan-owasp
    file: scripts/task-owasp.yml
    config:
      params:
        LIVE_TARGET: {{live-target}}
  - put: zap-collector
    params:
      from: results/zap.txt

