resources:
- name: scripts 
  type: git
  source:
    uri: https://github.com/18F/concourse-compliance-testing.git
    branch: {{script-branch}} 

jobs:
- name: zap-scan 
  plan:
  - get: scripts 
  - task: scan-owasp
    file: scripts/task-owasp.yml
    config:
      params:
        S3_ACCESS_KEY: {{aws-access-key}}
        S3_SECRET_KEY: {{aws-secret-key}}
        S3_BUCKET: {{aws-bucket}}

