---
inputs:
- name: projects-json
- name: scripts
outputs:
- name: results
platform: linux
image_resource:
  type: docker-image
  source:
    repository: ruby
    tag: '2.3-alpine'
run:
  path: ruby
  args:
  - ./scripts/tasks/filter-team-data/task.rb
