# Pipeline that clones this repository, then uploads it to S3. Built to test
#
#   https://github.com/18F/s3-resource-simple
#
# Local usage:
#
#   cp credentials.example.yml credentials.yml
#   # fill in credentials.yml
#   fly set-pipeline -t lite -n -c pipelines/custom-resource.yml -p custom-resource --load-vars-from credentials.yml
#
resource_types:
- name: s3-upload
  type: docker-image
  source:
    repository: 18fgsa/s3-resource-simple
resources:
- name: scripts
  type: git
  source:
    uri: https://github.com/18F/concourse-compliance-testing.git
    branch: master
- name: s3-bucket
  type: s3-upload
  source:
    access_key_id: {{aws-access-key}}
    secret_access_key: {{aws-secret-key}}
    bucket: {{aws-bucket}}
jobs:
- name: custom-resource-example
  plan:
  - get: scripts
  - put: s3-bucket
