# local usage:
#
#   fly set-pipeline -t lite -n -c pipelines/health-check.yml -p health-check -v script-branch=`git rev-parse --abbrev-ref HEAD`
#
resource_types:
- name: http-resource 
  type: docker-image
  source:
    repository: 18fgsa/http-resource
resources:
- name: scripts
  type: git
  source:
    uri: https://github.com/18F/concourse-compliance-testing.git
    branch: {{script-branch}}
- name: fetch-project-data
  type: http-resource
  source:
    uri: https://team-api.18f.gov/public/api/projects/
    filename: projects.json
    index: https://team-api.18f.gov/public/api/projects/
    etag: true
jobs:
- name: health-check
  plan:
  - get: scripts
  - get: projects-json
    resource: fetch-project-data
  - task: filter-team-data
    file: scripts/tasks/filter-team-data/task.yml
  - task: uptime-check
    file: scripts/tasks/uptime-check/task.yml
