# local usage:
#
#   fly set-pipeline -t lite -n -c pipelines/zap-ondemand.yml -p zap-ondemand -v script-branch=master
#
resources:
- name: scripts
  type: git
  source:
    uri: https://github.com/18F/concourse-compliance-testing.git
    branch: {{script-branch}}
- name: slack
  type: slack-notification
  source:
    url: {{slack-hook}}

jobs:
- name: zap-scan
  plan:
  - get: scripts
  - task: scan-zap
    file: scripts/tasks/run-zap/task.yml
    config:
      params:
        AWS_ACCESS_KEY_ID: {{aws-access-key}}
        AWS_SECRET_ACCESS_KEY: {{aws-secret-key}}
        S3_BUCKET: {{aws-bucket}}
  - put: slack
    params:
      channel: {{slack-channel}}
      icon_url: {{slack-icon}}
      text: |
        :white_check_mark: Completed scan of configured properties.
        <https://compliance-viewer.18f.gov/results|View results>
      username: {{slack-user}}
