resources:
- name: scripts 
  type: git
  source:
    uri: {{script-repo}}
    branch: {{script-branch}} 
- name: slack
  type: slack-notification
  source:
    url: {{slack-hook}} 

jobs:
- name: zap-scan 
  plan:
  - get: scripts 
  - task: scan-zap
    file: scripts/tasks/task-zap.yml
    config:
      params:
        S3_ACCESS_KEY: {{aws-access-key}}
        S3_SECRET_KEY: {{aws-secret-key}}
        S3_BUCKET: {{aws-bucket}}
  - put: slack
    params:
      channel: {{slack-channel}}
      icon_url: {{slack-icon}} 
      text: |
        :white_check_mark: Completed scan of configured properties.
        <https://compliance-viewer.18f.gov/results|View results>
      username: {{slack-user}} 
