# local usage:
#
#   fly set-pipeline -t lite -n -c pipelines/zap.yml -p zap --load-vars-from config/local.yml -v script-branch=`git rev-parse --abbrev-ref HEAD` -v project-data-url=URL
#
# where URL is of the form `https://team-api.18f.gov/public/api/projects/<name>/`.
resource_types:
- name: slack-notification
  type: docker-image
  source:
    repository: cfcommunity/slack-notification-resource
    tag: v1.0.0
- name: s3-resource
  type: docker-image
  source:
    repository: 18fgsa/s3-resource-simple
    tag: 1.1.1
- name: http-resource
  type: docker-image
  source:
    repository: 18fgsa/http-resource

resources:
- name: scripts
  type: git
  source:
    uri: https://github.com/18F/concourse-compliance-testing.git
    branch: {{script-branch}}
- name: slack
  type: slack-notification
  source:
    url: {{slack-hook}}
- name: s3-bucket-results
  type: s3-resource
  source:
    access_key_id: {{aws-access-key}}
    secret_access_key: {{aws-secret-key}}
    bucket: {{aws-bucket}}
    options:
      - "--exclude '*'"
      - "--include 'results/*'"
- name: s3-bucket-summary
  type: s3-resource
  source:
    access_key_id: {{aws-access-key}}
    secret_access_key: {{aws-secret-key}}
    bucket: {{aws-bucket}}
    options:
      - "--exclude '*'"
      - "--include 'zap-summary/summary.json'"
- name: fetch-project-data
  type: http-resource
  source:
    uri: {{project-data-url}}
    filename: project.json
    index: {{project-data-url}}
    etag: true

jobs:
- name: zap-single
  plan:
  - get: scripts
  - get: project-data
    resource: fetch-project-data
  - get: s3-bucket-results
  - task: fetch-last-zap-results
    file: scripts/tasks/fetch-last-zap-results.yml
  - task: scan-zap
    file: scripts/tasks/run-zap/task.yml
  - put: s3-bucket-results
  - task: summarize-zap-results
    file: scripts/tasks/summarize-zap-results/task.yml
  - put: s3-bucket-summary
    on_success:
      put: slack
      params:
        channel: {{slack-channel}}
        icon_url: {{slack-icon}}
        text_file: zap-summary/summary.txt
        username: {{slack-user}}
    on_failure:
      put: slack
      params:
        text: |
          :x: FAILED to scan properties.
          <https://ci.cloud.gov/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME|View build details>
        channel: {{slack-channel}}
        username: {{slack-user}}
        icon_url: {{slack-icon}}
