# local usage:
#
#   fly set-pipeline -t lite -n -c pipelines/zap.yml -p zap --load-vars-from config/local.yml -v script-branch=`git rev-parse --abbrev-ref HEAD`
#

# Previously we defined the slack notification as a resource, but the one on
# docker hub (https://hub.docker.com/r/nopik/slack-notification-resource/) is
# outdated. Instead, we ae using cloud.gov's built-in version
# (https://github.com/18F/slack-notification-resource-boshrelease).
resource_types:
- name: s3-upload
  type: docker-image
  source:
    repository: 18fgsa/s3-resource-simple
resources:
- name: scripts
  type: git
  source:
    uri: https://github.com/18F/concourse-compliance-testing.git
    branch: {{script-branch}}
- name: after-midnight
  type: time
  source:
    interval: 1h
    start: 12:00 AM -0500
    stop: 12:30 AM -0500
- name: slack
  type: slack-notification
  source:
    url: {{slack-hook}}
- name: s3-bucket
  type: s3-upload
  source:
    access_key_id: {{aws-access-key}}
    secret_access_key: {{aws-secret-key}}
    bucket: {{aws-bucket}}
    options:
      - "--exclude '*'"
      - "--include 'results/*'"
jobs:
- name: zap-scheduled
  plan:
  - get: after-midnight
    trigger: true
  - get: scripts
  - task: scan-zap
    file: scripts/tasks/run-zap/task.yml
  - put: s3-bucket
  - put: slack
    params:
      channel: {{slack-channel}}
      icon_url: {{slack-icon}}
      text: |
        :white_check_mark: Completed scan of configured properties.
        <https://compliance-viewer.18f.gov/results|View results>
      username: {{slack-user}}
- name: zap-ondemand
  plan:
  - get: scripts
  - task: scan-zap
    file: scripts/tasks/run-zap/task.yml
  - put: s3-bucket
  - put: slack
    params:
      channel: {{slack-channel}}
      icon_url: {{slack-icon}}
      text: |
        :white_check_mark: Completed scan of configured properties.
        <https://compliance-viewer.18f.gov/results|View results>
      username: {{slack-user}}
