# aws access controls
aws-access-key:
aws-secret-key:
# name of the S3 bucket to use
aws-bucket:
# the branch to use for the scripts repo
script-branch:
# webhook for Slack (described here: https://api.slack.com/incoming-webhooks)
slack-hook:
# which channel should get notified?
slack-channel:
# name for the slack user
slack-user:
