<%# note that this pipeline file is actually an ERB template, and thus shouldn't be used with `fly` directly -%>
groups:
<% projects.each do |project| -%>
- name: <%= project['name'] %>
  jobs:
  - zap-scheduled-<%= project['name'] %>
  - zap-ondemand-<%= project['name'] %>
<% end -%>

resource_types:
- name: slack-notification
  type: docker-image
  source:
    repository: cfcommunity/slack-notification-resource
    tag: v1.0.0
- name: s3-resource
  type: docker-image
  source:
    repository: 18fgsa/s3-resource-simple
    tag: 1.1.1
- name: http-resource
  type: docker-image
  source:
    repository: 18fgsa/http-resource

resources:
- name: scripts
  type: git
  source:
    uri: https://github.com/18F/concourse-compliance-testing.git
    branch: {{script-branch}}
- name: after-midnight
  type: time
  source:
    interval: 1h
    start: 12:00 AM -0500
    stop: 12:30 AM -0500
- name: slack
  type: slack-notification
  source:
    url: {{slack-hook}}
- name: s3-bucket-results
  type: s3-resource
  source:
    access_key_id: {{aws-access-key}}
    secret_access_key: {{aws-secret-key}}
    bucket: {{aws-bucket}}
    options:
      - "--exclude '*'"
      - "--include 'results/*'"
- name: s3-bucket-summary
  type: s3-resource
  source:
    access_key_id: {{aws-access-key}}
    secret_access_key: {{aws-secret-key}}
    bucket: {{aws-bucket}}
    options:
      - "--exclude '*'"
      - "--include 'zap-summary/summary.json'"
<% projects.each do |project| -%>
- name: fetch-project-data-<%= project['name'] %>
  type: http-resource
  source:
    uri: https://team-api.18f.gov/public/api/projects/<%= project['name'].downcase %>/
    filename: project.json
    index: https://team-api.18f.gov/public/api/projects/<%= project['name'].downcase %>/
    etag: true
<% end -%>

jobs:
<% projects.each do |project| -%>
<% %w(scheduled ondemand).each do |job| -%>
- name: zap-<%= job %>-<%= project['name'] %>
<% if job == 'scheduled' -%>
  # use of the `time` Resource blocks manual triggering, so might as well remove the option
  disable_manual_trigger: true
<% end -%>
  plan:
<% if job == 'scheduled' -%>
  - get: after-midnight
    trigger: true
<% end -%>
  - get: scripts
  - get: project-data
    resource: fetch-project-data-<%= project['name'] %>
  - get: s3-bucket-results
  - task: fetch-last-zap-results
    file: scripts/tasks/fetch-last-zap-results.yml
  - task: scan-zap
    file: scripts/tasks/run-zap/task.yml
  - put: s3-bucket-results
  - task: summarize-zap-results
    file: scripts/tasks/summarize-zap-results/task.yml
  - put: s3-bucket-summary
    on_success:
      put: slack
      params:
        channel: {{slack-channel}}
        icon_url: {{slack-icon}}
        text_file: zap-summary/summary.txt
        username: {{slack-user}}
    on_failure:
      put: slack
      params:
        text: |
          :x: FAILED to scan properties.
          <https://ci.cloud.gov/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME|View build details>
        channel: {{slack-channel}}
        username: {{slack-user}}
        icon_url: {{slack-icon}}
<% end -%>
<% end -%>
