require_relative '../../lib/team_data_filterer'
require_relative 'lib/pipeline_builder'

def branch
  `git rev-parse --abbrev-ref HEAD`.strip
end

desc "Set the deployment target to be local."
task :local do
  @config = 'local'
  @origin = 'http://192.168.100.4:8080'
  @target = 'lite'
end

desc "Set the deployment target to be ci.cloud.gov."
task :prod do
  @config = 'prod'
  @origin = 'https://ci.cloud.gov'
  @target = 'cloud'
end

desc "Build the ZAP pipeline."
task :build do
  builder = PipelineBuilder.new(TeamDataFilterer.targets)
  @file = Tempfile.create(['zap-pipeline', '.yml'])
  @file.write(builder.build)
  puts "INFO: Wrote pipeline to #{@file.path}."
end

task :verify_target do
  unless @config && @origin && @target
    task = Rake.application.top_level_tasks.last
    STDERR.puts "ERROR: No target set. Usage:\n\n  rake <target> #{task}\n\n"
    exit 1
  end
end

desc "Updates the pipeline."
task set: [:verify_target, :build] do
  config_path = File.expand_path("../../../config/#{@config}.yml", __FILE__)
  sh 'fly', 'set-pipeline',
    '-t', @target,
    '--load-vars-from', config_path,
    '-c', @file.path,
    '-n',
    '-p', 'zap',
    '-v', "script-branch=#{branch}"
end

desc "Unpauses the pipeline."
task unpause: :verify_target do
  sh 'fly', 'unpause-pipeline',
    '-t', @target,
    '--pipeline', 'zap'
end

desc "Open the pipeline in a browser."
task open: :verify_target do
  sh 'open', @origin
end

desc "Build and update the pipeline on the given target."
task deploy: [:build, :unpause, :open] do
  puts "INFO: Pipeline updated and unpaused."
end
